### ISSUE TITLE
detect option doesn't work

### ISSUE THREAD

**Issue by muhasturk** [lee-dohm/white-cursor#9]
Detect option enabled by me. However it did not work.

Atom 0.202

**Comment by lee-dohm** [comment]
What is the name of the syntax theme you have installed?

**Comment by muhasturk** [comment]
config.cson

```
"*":
  "exception-reporting":
    userId: "ccb703ec-6fba-df00-f0bc-1621ca69b534"
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "metrics"
    ]
    themes: [
      "seti-ui"
      "seti-syntax"
    ]
  editor:
    invisibles:
      {}
    showIndentGuide: true
    fontFamily: "source code pro"
  "white-cursor":
    enabled: "detect"
  linter:
    {}
  "atom-typescript":
    {}
```

**Comment by lee-dohm** [comment]
The detect mode expects the word "dark" to be somewhere in the name of the syntax theme. Since the Seti Syntax theme does not, it can't detect that you're using a dark theme. If you go to the settings for the white-cursor package and put "seti" in the list of dark theme names, it should detect just fine. For example, I put "railscasts" in my setup because I use a Railscasts syntax theme:

![screen shot 2015-05-28 at 5 23 21 pm](https://cloud.githubusercontent.com/assets/1038121/7874000/63e2fe98-055e-11e5-8fc0-75e16338575d.png)

**Comment by muhasturk** [comment]
Okey I see. Thank you for more information. This package should be included into Atom.

**Comment by lee-dohm** [comment]
Thanks. I should probably get around to submitting a PR for it at some point :grinning:
